// generated by warden_extract

#ifndef _WARDEN_MODULE_WIN_H
#define _WARDEN_MODULE_WIN_H

#include "Define.h"

struct WardenModuleWin
{
    uint8 Module[18439];
    uint8 ModuleKey[16];
    uint8 Seed[16];
    uint8 Hash[32];
    uint8 ServerKeySeed[16];
    uint8 ClientKeySeed[16];
    uint8 ClientKeySeedHash[20];
};

extern WardenModuleWin const winWardenModule;

#endif
